"""Backend cost per stage - the Feasibility slide's chart, in the house palette.

The deck already carried a version of this chart, generated by whatever made
the original six slides. **The numbers in it were right** - they match
`docs/test-plan.md` §4 exactly, median of 15 runs from
`benchmarks/bench_backend.py` - so nothing here is re-measured. What changed is
that it used its own four colours, and the deck now has nine other figures
sharing one palette. A chart that is the only thing on the page using a
different blue is a chart that looks borrowed.

**Why this chart is worth a slide at all.** The backend is a single-threaded
event loop, so a slow synchronous call does not just make one request slow - it
delays every other request and the poller with it. The interesting fact is not
that the numbers are small; it is that the system runs at the left-hand group
and the right-hand group is the cliff it is deliberately kept away from.
"""

import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from figures_style import (
    ACCENT, AIRCRAFT, BACKEND, DPI, INK, MUTED, OK, SATELLITE, STORE,
    apply_base_style, _tint,
)

apply_base_style()

# docs/test-plan.md §4, median of 15 runs. Not re-measured here.
GROUPS = ["2,000 objects", "10,000 objects", "30,000 objects"]
STAGES = [
    ("Poll apply", AIRCRAFT, [0.70, 7.4, 14.4]),
    ("Bbox filter", SATELLITE, [0.57, 3.2, 9.2]),
    ("Thin to 2,000", BACKEND, [0.82, 9.1, 43.5]),
    ("Search", STORE, [1.60, 8.3, 24.2]),
]

fig = plt.figure(figsize=(7.8, 4.9))
ax = fig.add_axes([0.075, 0.175, 0.905, 0.60])

WIDTH = 0.19
for index, (label, colour, values) in enumerate(STAGES):
    positions = [g + (index - 1.5) * WIDTH for g in range(len(GROUPS))]
    ax.bar(positions, values, WIDTH * 0.88, label=label, color=_tint(colour, 0.22),
           edgecolor=colour, linewidth=1.2, zorder=3)
    for x, value in zip(positions, values):
        ax.text(x, value + 0.9, f"{value:g}", ha="center", va="bottom",
                fontsize=7.4, color=INK, fontweight="bold", zorder=4)

ax.set_xticks(range(len(GROUPS)))
ax.set_xticklabels(GROUPS, fontsize=9.2, fontweight="bold", color=INK)
ax.tick_params(axis="x", length=0, pad=8)
ax.tick_params(axis="y", labelsize=7.8, colors=MUTED, length=0)
ax.set_ylim(0, 50)
ax.set_yticks([0, 10, 20, 30, 40, 50])
ax.set_ylabel("milliseconds", fontsize=8.0, color=MUTED)
ax.grid(axis="y", color="#E2E8F0", linewidth=0.9, zorder=0)
ax.set_axisbelow(True)
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.spines["bottom"].set_color("#CBD5E1")

ax.legend(loc="upper left", bbox_to_anchor=(0.0, 1.10), ncol=4, frameon=False,
          fontsize=8.2, handlelength=1.1, handleheight=1.0, columnspacing=1.8)

fig.text(0.075, 0.93, "Backend cost per stage", fontsize=12.5,
         fontweight="bold", color=INK)
fig.text(0.075, 0.875,
         "Milliseconds on a single-threaded event loop, by objects held in the store."
         "  Median of 15 runs.",
         fontsize=8.2, color=MUTED)

# Where the system actually runs. The response cap is 2,000, so the left-hand
# group is the operating point and the rest of the chart is headroom.
ax.annotate("", xy=(-0.42, -7.8), xytext=(0.42, -7.8),
            annotation_clip=False,
            arrowprops=dict(arrowstyle="|-|,widthA=0.4,widthB=0.4",
                            color=ACCENT, linewidth=1.4))
ax.text(0.0, -9.6, "where the system runs — the 2,000 response cap, every stage under 2 ms",
        ha="center", va="top", fontsize=7.8, color=ACCENT, fontweight="bold",
        clip_on=False)

# Parked over the 2,000 group, which is two millimetres tall. Anywhere near
# the 30,000 group it sits on the 43.5 bar it is describing.
ax.text(-0.42, 47.0,
        "The cliff it is kept away from:\nthinning 30,000 objects costs 43.5 ms,\n"
        "and every other request waits behind it.",
        ha="left", va="top", fontsize=7.6, color=MUTED, linespacing=1.6,
        style="italic")

out = pathlib.Path(__file__).parent / "figures" / "2-1-backend-cost-per-stage.png"
fig.savefig(out, dpi=DPI)
print("wrote", out, out.stat().st_size, "bytes")
